version: '3.8'

services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: backend
      MYSQL_DATABASE: backend_toDo_list
      MYSQL_USER: backend
      MYSQL_PASSWORD: backend
    volumes:
      - db_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: backend
    ports:
      - "8086:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
